# Arquivo: .github/workflows/rollback.yml
name: Rollback Kong Staging Configuration

permissions:
  contents: write
  pull-requests: write
  actions: read
  deployments: write
  issues: write


on:
  workflow_call:
    inputs:
      files_to_apply:
        type: string
        required: true
      stable_commit_sha:
        type: string
        required: false
        default: ''
      pr_number_to_revert:
        type: string
        required: true
      environment:
        type: string
        required: true
      region:
        type: string
        description: "Region"
        required: true
      region-name:
        type: string
        description: "The name of region"
        required: true
      approvers:
        type: string
        description: "Lista de aprovadores"
        required: true

jobs:
  # approve_job:
  #   runs-on: ubuntu-latest
  #   environment: ${{inputs.dynamic_environment}}
  #   steps:
  #     - name: Aprovar Mudanças
  #       run: echo "Mudanças aprovadas para o ambiente '${{ inputs.dynamic_environment }}'"


  approve_job:
    runs-on: ubuntu-latest
    steps:
      - name: Aprovação manual para deploy
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ inputs.approvers }}
          minimum-approvals: 1
          issue-title: "Aprovação de Apply para Produção"
          issue-body: "Por favor, aprove o apply da branch `main` para ${{inputs.region}}."
        

  prepare-matrix:
    runs-on: ubuntu-latest
    needs: [approve_job]
    outputs:
      region: ${{ steps.set-matrix.outputs.matrix }}
      region-name: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Generate region matrix from input string
        id: set-matrix
        run: |
          region=$(echo '${{ inputs.region }}' | jq -R 'split(",")' | jq -c .)
          echo "matrix=$region" >> $GITHUB_OUTPUT

          region-name=$(echo '${{ inputs.region-name }}' | jq -R 'split(",")' | jq -c .)
          echo "region-name=$region-name" >> $GITHUB_OUTPUT

  rollback:
    needs: [prepare-matrix]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    strategy:
      fail-fast: false
      matrix:
        file: ${{ fromJson(inputs.files_to_apply) }}
        region: ${{ fromJson(needs.prepare-matrix.outputs.region) }}
        region-name: ${{ fromJson(needs.prepare-matrix.outputs.region-name) }}
    steps:
      - name: Checkout Code at Correct Version
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.stable_commit_sha }}

      - uses: kong/setup-deck@v1
        with:
          deck-version: 1.47.1

      - name: validate 
        run: |
          echo "job finished"
          echo "region: ${{ inputs.region }}"
          echo "region-name: ${{ inputs.region-name }}"

  create-revert-pr-manual:
    runs-on: ubuntu-latest
    needs: [rollback]
    permissions:
      contents: write
      pull-requests: write
      deployments: write
    steps:
    - name: 'Checkout da branch principal (com histórico mínimo)'
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
        ref: 'main'
        fetch-depth: 2

    - name: 'Configurar Git'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: 'Executar Rollback com Git Checkout e Criar PR'
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        PR_NUMBER=${{ inputs.pr_number_to_revert }} # Mantemos para o título do PR
        
        echo "Iniciando rollback da pasta 'services/' para o estado do commit anterior (main~1)"
        
        NEW_BRANCH="rollback-services-pr-${PR_NUMBER}-$(date +%s)"
        git checkout -b $NEW_BRANCH
        
        # Restauramos a pasta 'services/' para o estado do commit
        # PAI do último commit da main.
        git checkout main~1 -- 'services/'
        
        if ! git diff-index --quiet HEAD; then
          # O SHA do commit anterior pode ser obtido com 'git rev-parse HEAD~1'
          PARENT_SHA=$(git rev-parse --short HEAD~1)
          git commit -m "revert/restore service folder to commit state in ${PARENT_SHA}"
        else
          echo "Nenhuma mudança para reverter na pasta 'services/'."
        fi
        
        git push origin $NEW_BRANCH
        
        PARENT_SHA=$(git rev-parse --short HEAD~1)
        gh pr create \
          --base main \
          --head $NEW_BRANCH \
          --title "Rollback: Restore to commit ${PARENT_SHA}" \
          --body "Este PR executa um rollback na pasta \`services/\`, restaurando seu conteúdo para o estado anterior ao último merge. Isso foi acionado devido ao PR #${PR_NUMBER}."