# Arquivo: .github/workflows/rollback-logic.yml

name: (Reusable Test) Rollback Logic
on:
  workflow_call:
    inputs:
      stable_commit_sha:
        type: string
        required: true
      pr_number_to_revert:
        type: string
        required: true
      environment_name:
        type: string
        required: true
      files_to_revert:
        type: string
        required: true

jobs:
  apply-stable-state:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}
    strategy:
      fail-fast: false
      matrix:
        file: ${{ fromJson(inputs.files_to_revert) }}
    steps:
      - name: '1. Checkout do código na VERSÃO ESTÁVEL'
        uses: actions/checkout@v4
        with:
          # AQUI ESTÁ A MÁGICA:
          # Ele usa o SHA que foi passado como input para voltar o código no tempo.
          ref: ${{ inputs.stable_commit_sha }}

      - name: Setup Deck
        uses: kong/setup-deck@v1
        with:
          deck-version: 1.47.1

      - name: '2. Deck Sync Rollback para cada cluster'
        run: |
          echo "Revertendo o arquivo ${{ matrix.file }} para o estado do commit ${{ inputs.stable_commit_sha }}"

  # Job para criar o PR de reversão do código
  create-revert-pr:
    runs-on: ubuntu-latest
    needs: apply-stable-state
    if: success()
    steps:
      - name: 'Instalar/Atualizar gh CLI para a versão mais recente'
        run: |
          # Este é o script oficial de instalação do gh CLI para Debian/Ubuntu
          type -p curl >/dev/null || (sudo apt-get update && sudo apt-get install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-key.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-key.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-key.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-key.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt-get update \
          && sudo apt-get install gh -y
          echo "gh CLI instalado/atualizado:"
          gh --version

      - name: 'Checkout da branch principal para criar o PR'
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: 'Criar PR para reverter o código'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh pr revert ${{ inputs.pr_number_to_revert }} --body "Rollback automático executado pela pipeline."