# Arquivo: .github/workflows/rollback-logic.yml

name: (Reusable Test) Rollback Logic
on:
  workflow_call:
    inputs:
      stable_commit_sha:
        type: string
        required: true
      pr_number_to_revert:
        type: string
        required: true

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Rollback
        run: |
          echo "🚨 INICIANDO SIMULAÇÃO DE ROLLBACK..."
          echo "1. Faria checkout no commit estável: ${{ inputs.stable_commit_sha }}"
          echo "2. Aplicaria a configuração antiga nos 3 clusters."
          echo "3. Criaria um PR para reverter o PR #${{ inputs.pr_number_to_revert }}"
          echo "✅ Simulação de Rollback concluída."