name: TEST Update Repo with Kong Configuration Changes

permissions:
  contents: write
  pull-requests: write
  actions: read
  deployments: write

on:
  workflow_call:
    inputs:
      files_to_apply:
        type: string
        required: true
      stable_commit_sha:
        type: string
        required: false
        default: ''
      pr_number_to_revert:
        type: string
        required: true
      dynamic_environment:
        type: string
        description: "The name of dynamic environment"
        required: true
      commit_has_changes:
        type: boolean
        description: "Flag to indicate if the commit has changes"
        required: true
        default: false

jobs:
  execute-commit:
    runs-on: ubuntu-latest
    if: ${{ inputs.commit_has_changes }} == 'true'
    steps:
      - name: Checkout da branch principal (para contexto Git)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: 'main'
          fetch-depth: 0

      - name: Baixar artefato com arquivos revertidos
        uses: actions/download-artifact@v4
        with:
          name: reverted-files
          path: .

      - name: Configurar Git
        run: |
          git config --global user.name "payments-api-gateway[bot]"
          git config --global user.email "164028134+payments-api-gateway[bot]@users.noreply.github.com"

      - name: Commitar e Fazer Push para a Main
        run: |
          if ! git diff-index --quiet HEAD; then
            echo "Mudanças detectadas. Realizando commit e push..."
            git add .
            git commit -m "chore(rollback): Reverte arquivos modificados no PR #${{ inputs.pr_number_to_revert }}"
            
            echo "Fazendo push para a branch main..."
            git push origin main
            
            echo "Criando e fazendo push da tag de rollback..."
            TAG_NAME="rollback/pr-${{ inputs.pr_number_to_revert }}_$(date +"%Y%m%d%H%M%S")"
            git tag $TAG_NAME
            git push origin $TAG_NAME
            echo "Rollback concluído e tag ${TAG_NAME} criada."
          else
            echo "Nenhuma mudança detectada no workspace. Nenhum commit será feito."
          fi