name: TEST Update Repo with Kong Configuration Changes

permissions:
  contents: write
  pull-requests: write
  actions: read
  deployments: write

on:
  workflow_call:
    inputs:
      files_to_apply:
        type: string
        required: true
      stable_commit_sha:
        type: string
        required: false
        default: ''
      pr_number_to_revert:
        type: string
        required: true
      dynamic_environment:
        type: string
        description: "The name of dynamic environment"
        required: true

jobs:
  prepare-commit-and-diff:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      deployments: write
    outputs:
      COMMIT_HAS_CHANGES: ${{ steps.revert.outputs.COMMIT_HAS_CHANGES }}
    steps:
      - name: Checkout da branch principal
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: 'main'
          fetch-depth: 0

      - name: Reverter arquivos para gerar o diff
        id: revert
        run: |
          echo "Revertendo arquivos para gerar o diff..."
          
          readarray -t files_to_revert < <(echo '${{ inputs.files_to_apply }}' | jq -r '.[]')
          
          if [ ${#files_to_revert[@]} -eq 0 ]; then
            echo "Nenhum arquivo especificado para reverter."
            echo "COMMIT_HAS_CHANGES=false" >> $GITHUB_OUTPUT
          else
            echo "Arquivos a serem revertidos:"
            printf " - %s\n" "${files_to_revert[@]}"
            
            git checkout ${{ inputs.stable_commit_sha }} -- "${files_to_revert[@]}"
            echo "COMMIT_HAS_CHANGES=true" >> $GITHUB_OUTPUT
          fi

      - name: Publicar diff no Job Summary
        if: ${{ steps.revert.outputs.COMMIT_HAS_CHANGES }} == 'true'
        run: |
          GIT_DIFF=$(git diff --color=never HEAD)
          if [ ${#GIT_DIFF} -gt 60000 ]; then
            GIT_DIFF="$(echo "$GIT_DIFF" | head -c 60000)\n\n... (diff truncado por ser muito longo)"
          fi
          
          cat <<EOF >> $GITHUB_STEP_SUMMARY
          ## ⚠️ Aprovação Necessária para Rollback na \`main\`
          As seguintes alterações (reversão do PR #${{ inputs.pr_number_to_revert }}) serão commitadas diretamente na branch \`main\` após a sua aprovação.
          <details><summary>Clique para ver o diff completo</summary>
          
          \`\`\`diff
          $GIT_DIFF
          \`\`\`
          </details>
          
          **Por favor, revise cuidadosamente e aprove o passo seguinte para continuar.**
          EOF

      - name: Salvar alterações como artefato
        if: ${{ steps.revert.outputs.COMMIT_HAS_CHANGES }} == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: reverted-files
          path: .

  wait-for-approval:
    runs-on: ubuntu-latest
    needs: [prepare-commit-and-diff]
    environment: ${{inputs.dynamic_environment}}
    steps:
      - name: Aguardando aprovação
        run: |
          if [[ "${{ needs.prepare-commit-and-diff.outputs.COMMIT_HAS_CHANGES }}" == "false" ]]; then
            echo "Nenhuma mudança para reverter. Aprovação não é necessária."
          else
            echo "Aprovação concedida. Prosseguindo com o commit para a 'main'."
          fi

  execute-commit:
    runs-on: ubuntu-latest
    needs: [wait-for-approval, prepare-commit-and-diff]
    if: needs.prepare-commit-and-diff.outputs.COMMIT_HAS_CHANGES == 'true'
    steps:
      - name: Checkout da branch principal (para contexto Git)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: 'main'
          fetch-depth: 0

      - name: Baixar artefato com arquivos revertidos
        uses: actions/download-artifact@v4
        with:
          name: reverted-files
          path: .

      - name: Configurar Git
        run: |
          git config --global user.name "payments-api-gateway[bot]"
          git config --global user.email "164028134+payments-api-gateway[bot]@users.noreply.github.com"

      - name: Commitar e Fazer Push para a Main
        run: |
          if ! git diff-index --quiet HEAD; then
            echo "Mudanças detectadas. Realizando commit e push..."
            git add .
            git commit -m "chore(rollback): Reverte arquivos modificados no PR #${{ inputs.pr_number_to_revert }}"
            
            echo "Fazendo push para a branch main..."
            git push origin main
            
            echo "Criando e fazendo push da tag de rollback..."
            TAG_NAME="rollback/pr-${{ inputs.pr_number_to_revert }}_$(date +"%Y%m%d%H%M%S")"
            git tag $TAG_NAME
            git push origin $TAG_NAME
            echo "Rollback concluído e tag ${TAG_NAME} criada."
          else
            echo "Nenhuma mudança detectada no workspace. Nenhum commit será feito."
          fi